baseURL = "https://recurse.henrystanley.com/"
languageCode = "en-us"
title = "Henry @ RC S1"
theme = "natrium"
publishDir = "docs"
googleAnalytics = "UA-19413261-4"

[params]
  author = "Henry Stanley"
